autonomys/space-acres

- src/frontend.rs
- src/frontend/configuration.rs
- src/frontend/loading.rs
- src/frontend/running.rs
- src/main.rs
This creates `frontend` module and moves a lot of logic into it in order to make `main.rs` more manageable. It also provides an example of how to split things into components and organize messaging between them.
There is no new logic here, just code moved around.
Resolves https://github.com/nazar-pc/space-acres/issues/14.
> Frontend module refactoring

- Cargo.lock
- Cargo.toml
- src/main.rs
A way for users to figure it out on their own without knowing about OS directory layout too much.
Also bumped version because we'll want to make another release soon.
> Add system information page in "About" dialog that shows paths to config and logs

- src/main.rs
"Default" doesn't necessary mean dark theme, so should be left as is in order to match the rest of the system.
> Better dark theme support

- .github/workflows/release.yml
- .github/workflows/rust.yml
Also switches to ustream gvsbuild when running clippy and tests
Fixes https://github.com/nazar-pc/space-acres/issues/5
> GTK4 build caching in CI (Windows)

- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/main.rs
Addresses https://github.com/nazar-pc/space-acres/issues/13, but not fully because configuration can still only be done by editing config file manually for now
> Show information about multiple farms in UI during normal operation (no configuration yet)

- .github/workflows/release.yml
- .github/workflows/rust.yml
Will improve CI time by a few minutes
> Skip GTK4 building in CI in case of cache hit

- .github/workflows/release.yml
- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
https://github.com/subspace/subspace/releases/tag/gemini-3g-2023-dec-22
> Upgrade Subspace to the latest release

- Cargo.lock
- Cargo.toml
- src/backend/farmer.rs
This also includes `parity-db` update and should fix https://github.com/nazar-pc/space-acres/issues/56 (though GTK memory leak is still present and will be handled separately once new GTK release is out)
> Upgrade Subspace to the upcoming release

- Cargo.lock
- Cargo.toml
- res/app.css
- src/backend.rs
- src/backend/farmer.rs
- src/backend/utils.rs
- src/frontend/configuration.rs
- src/frontend/loading.rs
- src/frontend/new_version.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/main.rs
A few things here:
* Subspace and relm4 updates
* farm summary state (plotting/replotting/farming) is removed as redundant, the same information is now displayed on per-farm level
* Sectors visualization
Sectors visualization is rendering of a grid of squares, one per each sector on per-farm basis. Color and blinking of the farm corresponds to what happens to the sector:
* gray color for sectors that are not plotted yet
* light blue for sectors that are plotted and up to date
* yellow for sectors that are about to expire and are going to be replotted soon
* pink for expired sectors
* slowly blinking sector is being downloaded
* fast blinking red is being encoded
* slowly blinking light blue is being written to disk
Colors are selected to be a intuitive and to work with both light and dark …
> Sectors visualization

- src/frontend/running/farm.rs
GTK4 decides to not render anything if there are fewer items than `min-columns` :upside_down_face: But only in never versions of GTK4, naturally :upside_down_face:
> Fix sector visualization on small farms with less than 110G of space

- src/backend.rs
- src/backend/config.rs
- src/backend/networking.rs
- src/backend/node.rs
- src/frontend/configuration.rs
This is helpful if there is more than 1 Subspace instance on local network and ports are colliding with default configuration.
This is also the beginning of the advanced configuration in Space Acres :scream:
> Add advanced configuration for P2P port customization

- src/frontend/running/farm.rs
If min size matches exactly, nothing gets rendered :facepalm:
> Fix sector visualization on small farms (again)

- Cargo.lock
- Cargo.toml
- res/app.css
- src/backend/farmer.rs
- src/backend/node.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/frontend/running/node.rs
With these changes a few things are added:
* Auditing and proving performance indicators are shown with reasonable targets set, showing when performance is not acceptable (skipped proving is not shown yet though)
* Node sync speed is shown with expected remaining time
* Plotting/replotting speed is shown as both minutes per sector and sectors per hour
Resolves https://github.com/nazar-pc/space-acres/issues/77, resolves https://github.com/nazar-pc/space-acres/issues/34, resolves https://github.com/nazar-pc/space-acres/issues/12
Also with Subspace update NUMA enabling in BIOS is no longer necessary as farmer will check L3 cache topology instead.
> Visual performance indicators

- .github/workflows/release.yml
- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- README.md
- rust-toolchain.toml
- src/backend.rs
- src/backend/farmer.rs
- src/backend/farmer/maybe_node_client.rs
- src/backend/networking.rs
- src/backend/node.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
This updates Space Acres to become compatible with Gemini 3h.
However, before https://github.com/nazar-pc/space-acres/issues/106 can be resolved fully Space Acres needs to be able to detect Gemini 3g installation and support switching to 3h with a migration button in GUI. Only then new release with 3h support will be done.
> Subspace upgrade

- .github/workflows/release.yml
Ran a test build in CI from this branch, it works
> Add code signing on Windows

- res/windows/wix/space-acres.wxs
This should fix the problem of getting Space Acres installed twice if two builds are installed, but have the same version. Now second installation should replace the first one (as user would expect).
> Allow same version upgrades

- Cargo.lock
- Cargo.toml
This improves plot caching behavior and related memory usage on Windows.
On Windows plot caching is now disabled for farms over 2T.
> Update to upcoming Subspace release

- res/windows/wix/expected-dlls.log
- res/windows/wix/space-acres.wxs
fix gtk4 newest build error:
Throw "Actual DLLs do not match expected"
Actual DLLs do not match expected
Error: Process completed with exit code 1.
> Update DLLs to latest GTK4 build version

- .github/workflows/rust.yml
Otherwise it is not compatible with newer Rust compiler
> Fix cargo nextest by allowing to upgrade dependencies comparing to lock file

- res/windows/wix/space-acres.wxs
Windows packaging is just as painful to work with as their file system.
Basically due to not using one component per file, during upgrade with `MajorUpgrade.Schedule=afterInstallExecute` old files of matching components will not be deleted. As the result, those files will remain in `Program Files` forever.
This PR fixes that by manually deleting known old files for cleanup purposes and switching to one file per component going forward.
This also means that upgrade is a bit awkward because removing of the old `gtk4` component means installer will remove all the old files and leave the app broken, so it needs to be re-installed/repaired to restore the files. But it is better to handle this sooner rather than dealing with these issues indefinitely.
Fixes …
> Fix remaining files after upgrade on Windows

- .github/workflows/release.yml
- Cargo.toml
- res/windows/wix/space-acres.wxs
- src/main.rs
This change brings support for x86-64-v2 CPUs by shipping 2 binaries:
* normal binary is that is built for x86-64-v2, new default
* modern binary is that is build skylake
When application starts, it will do check for supported instructions and if CPU appears to support instructions that only Skylake and newer processors support, it will pick modern version of a binary to as a child process, otherwise it will continue with the default one.
Fixes https://github.com/subspace/space-acres/issues/135, fixes https://github.com/subspace/space-acres/issues/132
> Support legacy CPUs

- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/farmer.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/main.rs
Includes https://github.com/subspace/subspace/pull/2719
> Fix farm locking on Windows that leads to farm info file corruption by switching to upcoming Subspace release

- Cargo.lock
- Cargo.toml
- src/backend/node.rs
companion PR https://github.com/subspace/subspace/pull/2735
Before:
```bash
Building [===========>            ] 708/1336:
```
Now:
```bash
Building [=====================> ] 1257/1268
```
> Replace `subspace-runtime` with `subspace-fake-runtime-api`

- Cargo.lock
- Cargo.toml
- src/main.rs
Upstream regression affecting old Intel iGPUs (and maybe some others as well, but hard to tell)
> Force old GL renderer on old CPUs (and likely GPUs by extension) on Windows

- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/farmer.rs
- src/backend/farmer/direct_node_client.rs
- src/backend/farmer/maybe_node_client.rs
- src/backend/networking.rs
- src/backend/node.rs
closes #27 
Implementation is mostly borrowed from `SubspaceRpcApiServer` [implementation](https://github.com/subspace/subspace/blob/main/crates/sc-consensus-subspace-rpc/src/lib.rs#L311). I removed `deny_unsafe` feature, since this implementation is not exposed to outside and modified subscription functions.
I am still using the old way of instantiating a `NodeClient` implementation, i.e first default and then inject it once inner value is instantiated, to ensure it is easy to follow the changes. Should we change this, i.e don't wrap it in struct and `ArcSwapOption`?
I spent some time trying to implement your suggestion about dynamic `FullClientT` trait, however, couldn't manage to do it. The main blocker was the `ProvideRuntimeApi` which has an associated `Api` type which should be …
> Replace `NodeRpcClient` with direct `NodeClient` implementation for the client

- Cargo.lock
- Cargo.toml
- src/backend/farmer/direct_node_client.rs
Regression from https://github.com/subspace/space-acres/pull/192 that prevents farms from starting
@dastansam not sure why you changed it. Genesis hash and best hash are different things and it was correct in RPC implementation in monorepo.
> Fix genesis hash

- src/main.rs
The feedback TypeForm was swapped to a Linktree page, with more options for users to raise an issue, search for help or leave feedback. 
I changed the label on the button, can't say if it's going to be too long for the UI.
> Change feedback TypeForm to LinkTree

- src/frontend/running.rs
Looks like explorer navigation changed, this is the correct URL now
> Fix explorer URL

- Cargo.lock
- Cargo.toml
- src/frontend/new_version.rs
- src/frontend/running.rs
Use regular buttons rather than GtkLinkButton until GtkLinkButton if fixed on macOS: https://gitlab.gnome.org/GNOME/glib/-/issues/3403
> Fix opening links on macOS

- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/frontend/running/node.rs
Some buttons were not trivial to discover, use `pointer` cursor to indicate that certain area of the UI is clickable
> Use `pointer` cursor for less obvious clickable UI elements

- src/frontend/configuration.rs
- src/frontend/configuration/farm.rs
This PR adds macOS-specific example paths for the node and farm data.
The paths follow the pattern of Windows and Linux, which are on separate drives.
> Add macOS-specific example paths in configuration

- Cargo.lock
- Cargo.toml
This PR updates Subspace to [`gemini-3h-2024-jul-29`](https://github.com/autonomys/subspace/releases/tag/gemini-3h-2024-jul-29) release and bumps version.
> Update Subspace to `gemini-3h-2024-jul-29` release and bump version

- README.md
`space-acres` needs `librsvg` to show icons.
But `gtk-rs` doesn't explicitly document its optional dependency on `librsvg`, and `cargo build` doesn't install it automatically.
> Document `librsvg` dependency in README.md

- src/backend.rs
- src/backend/farmer.rs
- src/frontend/loading.rs
- src/frontend/running.rs
- src/main.rs
Resolves https://github.com/subspace/space-acres/issues/133.  change spinner to progressbar.
> feat: show loading progress

- docs/INSTALLATION.md
As discussed on Slack, some Wifi stacks slow down or hang when making large numbers of connections.
I found this issue on macOS 13.6.7 / MacBook Pro / M1 + Nokia Wifi Beacon 1.1, but other hardware/software combinations are also impacted.
> Document that Ethernet is preferred over Wifi in INSTALLATION.md

- Cargo.lock
- Cargo.toml
- build.rs
- res/translations/en/messages.ftl
- src/frontend/translations.rs
Follow-up to https://github.com/autonomys/space-acres/pull/258.
Had to prefix placeables/variables with `a_` and such for function argument order to be predictable due to https://github.com/zaytsev/fluent-static/issues/9 (which kind of makes sense, but was still surprising).
> Fix some translation errors

- Cargo.lock
- Cargo.toml
- src/main.rs
This will greatly help with debugging on Windows where stderr is not possible to capture with `#![windows_subsystem = "windows"]`
Fixes https://github.com/autonomys/space-acres/issues/188
> Capture panics on Windows as tracing events

- .cargo/config.toml
Same reasoning as in https://github.com/autonomys/subspace/pull/2964
> Remove .cargo/config and +aes feature on x86-64

- src/frontend.rs
Basically if Space Acres was minimized to tray and user tried to open Space Acres nothing was happening (because only one instance of Space Acres can be running at a time). With this change original app will be un-minimized when this happens, which is most likely what user expects.
> Show minimized app when attempting to open another instance

- Cargo.lock
- Cargo.toml
- src/frontend.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
Should fix icons on Linux, actually work on Windows (https://gitlab.gnome.org/GNOME/glib/-/issues/1234) and even on macOS it should work even though I didn't test it there
> Replace desktop notification implementation with `notify-rust` that actually works and even supports icons

- .github/workflows/release.yml
- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- README.md
- res/translations/de-DE/messages.ftl
- res/translations/en/messages.ftl
- res/translations/rs/messages.ftl
- res/translations/ru-RU/messages.ftl
- res/translations/zh-CN/messages.ftl
- src/frontend.rs
- src/frontend/tray_icon.rs
- src/frontend/tray_icon/unix.rs
- src/frontend/tray_icon/windows_macos.rs
closes #222 
tested on MacOS
https://github.com/user-attachments/assets/f2f14388-e926-43d9-842d-38381c734e19
> Use `tray_icon` crate for better tray icon support

- .github/workflows/release.yml
- .github/workflows/rust.yml
Caused by https://github.com/wingtk/gvsbuild/issues/1436
> Roll back gvsbuild to older stable release

- .github/workflows/release.yml
- .github/workflows/rust.yml
- docs/INSTALLATION.md
Windows 10 and Ubuntu 22.04/22.10/23.04/23.10 are no longer officially supported. They may still work with official or unofficial builds, but nothing is guaranteed anymore.
> Update OS requirements

- Cargo.lock
- Cargo.toml
- src/frontend.rs
Errors no longer cause window becoming huge and error message can be copied
> Switch to relm4-icons upstream pre-release and improve error display

- .github/workflows/release.yml
Should fix installation on Windows after https://github.com/autonomys/space-acres/pull/324 due to installation of unsigned .msi being not supported from signed .exe and resulting in errors like these:
```
[35E8:365C][2024-11-09T22:31:08]e312: Failed to extract payloads from container: WixAttachedContainer to working path: C:\Windows\Temp{2659BD1A-AD4F-41E3-97FB-DD05575D9E94}\2921D55D9706507495DD58643508D385E5DF6629, error: 0x80070001.
[35E8:35EC][2024-11-09T22:31:08]e000: Error 0x80070001: Failed while caching, aborting execution.
[3638:363C][2024-11-09T22:31:08]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall{ffa4f922-d8d4-4015-a8f7-78572989ff15}, resume: None, restart: None, disable resume: No
[3638:363C][2024-11-09T22:31:08]i330: Removed bundle …
```
> Sign both outer bundle and inner installer on Windows

- res/windows/wix/space-acres.wxs
Forgot this when adding bundle in https://github.com/autonomys/space-acres/pull/324. This is needed because Visual C++ Redistributable is only installed after successful installation of the app, so having this checkbox enabled will result in an error because the complete installation is not done yet.
> Remove "Run Space Acres" action on Windows after installation

- Cargo.toml
This appears to be more correct and allows to render correct icon in the dash in GNOME desktop
> Change the location of an icon file in deb package

- res/translations/es/messages.ftl
Removed todo translation in `es`
> Spanish translation of `running_node_connections_tooltip`

- src/frontend/new_version.rs
- src/frontend/running.rs
- src/frontend/running/node.rs
Now that macOS bug was fixed, we can switch back to `LinkButton`
> Switch to LinkButton

- Cargo.lock
- Cargo.toml
- src/main.rs
In https://github.com/autonomys/space-acres/issues/361 it was discovered that on macOS segfault causes process to exit with code `11`, while on Linux it exits with `SIGSEGV`.
This change will support exit with unexpected status codes (like `11` on macOS) as a reason for application restart like like termination with a signal on Linux.
The first commit here improves logs handling by capturing supervisor logs in log file, which were missing previously, this will help with debugging in the future by providing details about why process exited.
> Improve crash handling on macOS

- .github/workflows/release.yml
Linux aarch64 runners are available for public repos, so let's use them: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
CUDA support is missing for now due to some bugs in Ubuntu packages: https://bugs.launchpad.net/ubuntu/+source/mumax3/+bug/2032624
But that shouldn't prevent us from shipping an app as such.
> Add `aarch64` Linux build to releases

- Cargo.lock
- Cargo.toml
- src/frontend/running.rs
- src/frontend/running/node.rs
This fixes reward ETA calculation (it was using cache size instead of space pledged minus cache size for estimation and was 99x off as the result :grimacing: ).
Also network indicator gets green before reaching 40 peers since even a few less peers is perfectly fine.
> Small fixes

- Cargo.lock
- Cargo.toml
- build.rs
- res/windows/wix/expected-dlls.log
- res/windows/wix/space-acres.wxs
- rust-toolchain.toml
- rustfmt.toml
- src/backend.rs
- src/backend/config.rs
- src/backend/farmer.rs
- src/backend/farmer/direct_node_client.rs
- src/backend/networking.rs
- src/backend/node.rs
- src/frontend.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/frontend/running/node.rs
- src/frontend/translations.rs
- src/main.rs
- Bumps substrate and subspace deps
- Bumps Rust toolchain to nightly used on subspace
- Migrated to 2024 rust edition as clippy warns are coming from subspace as it is using 2024 edition
- Remove lite-p2p patch as webrtc is made optional and its deps are not being included
- Patched libp2p and identity to our fork due to deps coming from different sources
- No logical changes but rather changes made to make clippy happy and errors coming due to 2024 edition.
Should be a straightforward review but focus on lock file if there is anything unexpected you see that I may have missed.
Running a local space-acres and everything seems okay with syncing with low peers as are seeing with latest pre-release on mainnet.
> Update substrate and subspace deps, rust toolchain and migrate to 2024 edition

- src/backend/networking.rs
This PR documents that the `NetworkOptions` are (mostly) used for the DSN.
This was confusing for me, so it seems useful to make it explicit.
> Document network options are for DSN

- res/translations/de-DE/messages.ftl
- res/translations/en/messages.ftl
- res/translations/es/messages.ftl
- res/translations/fr/messages.ftl
- res/translations/ru-RU/messages.ftl
- res/translations/sr-Latn-RS/messages.ftl
- res/translations/tr/messages.ftl
- res/translations/uk-UA/messages.ftl
- res/translations/zh-CN/messages.ftl
The signature tooltip says ", expand farm details to see more information", but there is no information about signatures in the farm details. This is confusing.
The existing "Expand details about each farm" tooltip at the top of the farm list seems like enough.
This PR removes that text in every translation, using Cursor with the prompt:
```
Delete this text in every translation: ", expand farm details to see more information"
```
I have verified the English and French translations, the Spanish, German and Serbian look right, and the rest follow the structure of the English sentences.
> Remove reference to non-existent 'more information' from signature tooltip

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- res/windows/wix/expected-dlls.log
- res/windows/wix/space-acres.wxs
- src/backend.rs
- src/backend/farmer.rs
- src/backend/farmer/direct_node_client.rs
- src/backend/farmer/maybe_node_client.rs
- src/backend/networking.rs
- src/main.rs
This PR updates subspace to bring in the piece cache slot fix:
- https://github.com/autonomys/subspace/pull/3677
We also moved some code around and added new trait methods in `subspace` in:
- https://github.com/autonomys/subspace/pull/3660
- https://github.com/autonomys/subspace/pull/3659
- https://github.com/autonomys/subspace/pull/3669
- https://github.com/autonomys/subspace/pull/3678
This PR fixes those imports and adds the new trait methods. It also documents why the security fixes in https://github.com/autonomys/subspace/pull/3660 weren't needed here.
~~It's a draft until all those `subspace` PRs merge, then I'll update the subspace dependency to the main branch.
I'm posting it now so these fixes are ready, even if I'm away.~~
> Update subspace for piece cache slot fix
