autonomys/space-acres

- .cargo/config.toml
- .github/workflows/release.yml
- README.md
- src/main.rs
- wix/space-acres.wxs
A bunch of manually crafted instructions in wix file to work around https://github.com/volks73/cargo-wix/issues/271. Fragile, but it works for now.
> Fix Windows installer and other tweaks

- src/backend.rs
- src/backend/farmer.rs
- src/backend/node.rs
- src/frontend/configuration.rs
- src/frontend/running.rs
- src/main.rs
This handles initial status of node and farmer as well as piece can sync progress of https://github.com/nazar-pc/space-acres/issues/12
I also found some minor UI glitches that I fixed too.
> Better node farmer status

- res/app.css
- src/backend.rs
- src/backend/config.rs
- src/frontend/configuration.rs
- src/main.rs
Partially implements https://github.com/nazar-pc/space-acres/issues/16
> Support configuration changes using graphical interface

- src/backend.rs
- src/backend/farmer.rs
- src/frontend/running.rs
- src/main.rs
Fixes https://github.com/nazar-pc/space-acres/issues/35
> Initialize plotting state correctly if initial plotting is done

- src/main.rs
Resolves https://github.com/nazar-pc/space-acres/issues/26
> Support application restart on configuration changes

- src/frontend/running.rs
Target is set to `0` when all blocks are already local and importing, but we should still show that remaining progress finishing
> Fix node sync state by handling potentially disappearing target when node is almost synced

- Cargo.lock
- Cargo.toml
- src/backend/farmer.rs
Upgrade to https://github.com/subspace/subspace/releases/tag/gemini-3g-2023-dec-18-2
> Upgrade Subspace to the latest release

- Cargo.lock
- Cargo.toml
- src/frontend/configuration.rs
- src/main.rs
This fixes some icons not rendering on Windows at all too
> Render icons properly in cross-platform way

- src/frontend/running.rs
> Fix existing balance tracking that caused subtraction with overflow

- src/backend.rs
- src/backend/node.rs
- src/frontend/running.rs
- src/main.rs
Resolves https://github.com/nazar-pc/space-acres/issues/11 fully
> Link to Astral for details about balance, chain name and token symbol from chain spec

- .github/workflows/release.yml
- res/windows/wix/space-acres.wxs
This is the only thing that is actually being used
> Only ship compiled schemas

- src/frontend/configuration.rs
- src/frontend/configuration/farm.rs
- src/frontend/running.rs
Resolves https://github.com/nazar-pc/space-acres/issues/13 fully
> Multiple farms configuration

- Cargo.lock
- Cargo.toml
- src/frontend.rs
- src/frontend/new_version.rs
- src/main.rs
Resolves https://github.com/nazar-pc/space-acres/issues/17 by checking new version every hour and showing a button that leads to releases page when new version is found
> Implement new version check

- Cargo.lock
- Cargo.toml
- res/app.css
- src/backend/node.rs
- src/frontend/running.rs
- src/frontend/running/node.rs
Resolves first item from https://github.com/nazar-pc/space-acres/issues/81 by monitoring free disk space and warning starting with 10GiB, while node will shut down once free disk space gets to 1GiB. This should give enough time for user to resolve the situation.
> Free disk space monitoring of the node path

- src/frontend/running/farm.rs
- src/frontend/running/node.rs
> Add spacing between different indicators

- Cargo.lock
- Cargo.toml
- src/frontend/running/farm.rs
This updates Subspace to newer revision of upcoming release to handle sector metadata corruption on restart and adds visual warning for non-fatal farming error of each farm.
> Graceful farmer error handling

- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/farmer.rs
- src/main.rs
Updates subspace to https://github.com/subspace/subspace/releases/tag/gemini-3g-2024-jan-31
> Update to latest Subspace release

- Cargo.lock
- Cargo.toml
- src/frontend/configuration.rs
- src/main.rs
Resolves https://github.com/nazar-pc/space-acres/issues/9
> Add welcome screen

- src/backend.rs
- src/backend/config.rs
- src/backend/farmer.rs
- src/backend/node.rs
- src/frontend/loading.rs
- src/main.rs
This fixes some stuff that were wrong in https://github.com/nazar-pc/space-acres/pull/107 and introduces support for upgrade from Gemini 3g to Gemini 3h.
Resolves https://github.com/nazar-pc/space-acres/issues/106
> Support upgrade from 3g

- Cargo.lock
- Cargo.toml
- res/app.css
- src/frontend/running/farm.rs
Fixes https://github.com/nazar-pc/space-acres/issues/119 and renders sector state as text in tooltip
> Improve sectors visualization rendering

- .github/workflows/release.yml
- .github/workflows/rust.yml
Similar to https://github.com/subspace/subspace/pull/2555
> Remove LLVM workarounds in CI

- res/windows/wix/space-acres.wxs
This should preserve shortcuts pinned to start menu and taskbar on upgrade
> Improve upgrade on Windows by not removing shortcuts

- Cargo.lock
- Cargo.toml
Fixes https://github.com/subspace/space-acres/issues/117
> Update Subspace to reduce memory usage during farmer on Windows

- Cargo.lock
- Cargo.toml
- res/app.css
- src/backend.rs
- src/backend/farmer.rs
- src/main.rs
This includes https://github.com/subspace/subspace/pull/2623
> Update to upcoming Subspace release

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
See https://github.com/supranational/blst/issues/207
> Fix legacy support bue to blst library not recompiling itself on CPU change

- Cargo.toml
- src/frontend/running.rs
- src/frontend/running/farm.rs
This was requested by some users, especially when they have a lot of space pledged with multiple farms
> Add toggle for expanding farm details

- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/farmer.rs
- src/backend/networking.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/main.rs
This was requested by some community members
> Add button to pause plotting

- Cargo.lock
- Cargo.toml
- res/app.css
- src/backend/farmer.rs
- src/frontend/configuration.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
With this change instead of failing completely Space Acres will survive farm errors and will show individual farm errors while other farms can continue to farm/plot/replot normally
> Farm error handling

- .github/workflows/release.yml
- .github/workflows/rust.yml
- res/windows/wix/expected-dlls.log
- res/windows/wix/space-acres.wxs
Similar to https://github.com/subspace/subspace/pull/2663
> Update GitHub actions versions

- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/farmer.rs
- src/backend/networking.rs
- src/frontend/running.rs
Also indirect dependencies were updated
> Update Subspace to gemini-3h-2024-may-01

- src/main.rs
Resolves https://github.com/subspace/space-acres/issues/154.  have tried linkbutton, but the style is not consistent with other button. so use button and uri launcer solution.
> feat: add feedback button

- Cargo.lock
- Cargo.toml
- src/backend/node.rs
Missed new state pruning default :disappointed:
> Fix upgrade from older versions

- src/main.rs
Root cause and solution are the same as https://github.com/subspace/space-acres/pull/216
> Fix "Share feedback" button on macOS

- src/main.rs
Disable it for now since it is not quite working properly, see https://github.com/subspace/space-acres/issues/183 and https://github.com/subspace/space-acres/issues/222
> Disable tray icon on macOS

- src/backend.rs
- src/backend/node.rs
- src/frontend.rs
- src/frontend/running.rs
- src/frontend/widgets.rs
- src/frontend/widgets/progress_circle.rs
- src/main.rs
Resolves https://github.com/subspace/space-acres/issues/86, based on https://github.com/subspace/space-acres/pull/206, so thanks to @abhi3700 for initial implementation there
> Next reward ETA implementation

- Cargo.lock
- Cargo.toml
- src/backend/config.rs
- src/frontend/configuration.rs
- src/frontend/configuration/farm.rs
- src/frontend/loading.rs
- src/frontend/new_version.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/frontend/running/node.rs
- src/frontend/widgets/progress_circle.rs
- src/main.rs
This refactors UI updates with tracker usage, which makes updates more efficient and allows to simplify code in some cases like removing `unknown` hacks.
The API still feels awkward, especially since we have to use `get_mut_x` on `x` field just to trigger its update even though the use case doesn't require mutable access. Hoping for more ergonomic and intuitive solution in the future.
Using tracker from https://github.com/AaronErhardt/Tracker/pull/12 for more concise API
> Tracker refactoring

- Cargo.lock
- Cargo.toml
- res/app.css
- src/frontend/configuration.rs
- src/frontend/configuration/farm.rs
- src/main.rs
A collection of small UI improvements:
* checkbox and x at the end of fields are now green/red based on field contents to better indicate correct/incorrect contents
* `Example: ` prefix added to placeholders
* "Help" button added to configuration screen
> UI improvements

- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/config.rs
- src/frontend/configuration.rs
- src/frontend/configuration/farm.rs
- src/frontend/configuration/utils.rs
- src/main.rs
This implements full reconfiguration support to recover from errors.
UI will also show path errors and prevent from moving forward if user doesn't have write permissions in the directory, which will avoid annoying issue some users were facing before.
Resolves https://github.com/subspace/space-acres/issues/16, fixes https://github.com/subspace/space-acres/issues/218, resolves https://github.com/subspace/space-acres/issues/226
> Full reconfiguration

- src/main.rs
Not happy that we have two menu buttons that we show alternatively, but this was the nicest workaround I have found.
Resolves https://github.com/subspace/space-acres/issues/33
> Use proper menu in popover

- Cargo.toml
- res/app.css
- src/frontend/running/farm.rs
Show signing success rate, optimize UI clutter for each farm unless details are enabled
> Signing success rate

- src/main.rs
In continuation of a rebranding effort, updating the link to a newer linktree with Autonomys branding. Thanks!
Fixes https://github.com/autonomys/space-acres/issues/248
> Update share feedback link to lead to Autonomys linktree

- src/frontend/configuration/farm.rs
Fixes https://github.com/autonomys/space-acres/issues/247
> Fix `Save` button not working until non-advanced configuration is changed

- .cargo/config.toml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/farmer.rs
- src/backend/networking.rs
Includes https://github.com/autonomys/subspace/pull/2956
> Update Subspace to the latest `main` and remove unnecessary ARMv8 workarounds

- src/frontend/configuration.rs
This appears to be a common issue for users, let's have a dedicated message rather than just a red `x`
> Catch EVM address and provide a helpful error message

- src/main.rs
Resolves https://github.com/autonomys/space-acres/issues/58
> Better error handling with helpful next steps

- Cargo.lock
- Cargo.toml
- build.rs
- res/translations/README.md
- res/translations/en/messages.ftl
- src/backend/node.rs
- src/frontend.rs
- src/frontend/configuration.rs
- src/frontend/configuration/farm.rs
- src/frontend/loading.rs
- src/frontend/new_version.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/frontend/running/node.rs
- src/frontend/translations.rs
We're ready for Space Acres to be translated into various languages now.
Resolves https://github.com/autonomys/space-acres/issues/215
> Basic setup for UI translations

- res/translations/rs/messages.ftl
Contextually correct translation to Serbian language to the best of my ability.
> RS (Serbian) language file added.

- src/frontend.rs
Space Acres troubleshooting page was added as per discussion in [issue 58](https://github.com/autonomys/space-acres/issues/58)
> Update community help link to lead to Space Acres troubleshooting page

- res/translations/en/messages.ftl
- res/translations/rs/messages.ftl
- res/translations/zh-CN/messages.ftl
- src/frontend.rs
- src/main.rs
Fixes https://github.com/autonomys/space-acres/issues/54
> Better shutdown handling

- res/translations/en/messages.ftl
- res/translations/rs/messages.ftl
- res/translations/zh-CN/messages.ftl
- src/frontend.rs
- src/main.rs
If application was able to run for at least 30 seconds before crashing, it will be brought back up again.
Resolves https://github.com/autonomys/space-acres/issues/134.
> Restart on crash

- res/translations/de-DE/messages.ftl
This PR adds the German Language Support for the Space Acres interface
> Add German Language Support for Space Acres

- res/translations/zh-CN/messages.ftl
> Update zh-CN translation

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/backend.rs
- src/backend/farmer.rs
- src/backend/farmer/direct_node_client.rs
- src/backend/farmer/maybe_node_client.rs
- src/backend/networking.rs
- src/backend/node.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
Also includes related updates from there that happened during the same time as well as update of all dependencies
> Update Subspace to latest `main` revision

- .github/workflows/release.yml
- .github/workflows/rust.yml
The same as https://github.com/autonomys/subspace/pull/3172
> Remove msys64 workaround

- Cargo.lock
- Cargo.toml
- build.rs
- src/frontend.rs
- src/frontend/configuration.rs
- src/frontend/configuration/farm.rs
- src/frontend/running.rs
- src/frontend/running/farm.rs
- src/frontend/running/node.rs
- src/main.rs
Based on https://github.com/autonomys/space-acres/pull/265
> Update `relm4` and `gtk4` to newer versions

- docs/INSTALLATION.md
- res/macos/StepToCreateDmg.md
- res/translations/README.md
Cleaned up the sentence to make it clearer. Hope this helps.
> docs: cleanup the sentences

- .github/workflows/release.yml
Fixes https://github.com/autonomys/space-acres/issues/333
> Fix SVG in AppImage

- res/translations/de-DE/messages.ftl
> Update German translation

- res/translations/zh-CN/messages.ftl
Ambiguity in the translation.  Original in English, it means we will have more reward chance. not "missing reward chance",  ignore this pull request if I'm wrong
> Update CN messages.ftl
